# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_practice.User')),
            ],
        ),
    ]
