# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam_practice', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='joiner',
            field=models.ManyToManyField(related_name='joined_trips', to='exam_practice.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='new_description',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='new_destination',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
